/**
 * VINDecoderLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ValidVIN = require('../lib/Models/ValidVIN');
const InvalidVINEnteredException = require('../lib/Exceptions/InvalidVINEnteredException');
const NOVINEnteredException = require('../lib/Exceptions/NOVINEnteredException');
const VINNotFoundException = require('../lib/Exceptions/VINNotFoundException');

const classMap = {
    ValidVIN,
    InvalidVINEnteredException,
    NOVINEnteredException,
    VINNotFoundException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
